export const skills = [
  {name: "boating",       attribute: "agility"},
  {name: "climbing",      attribute: "strength"},
  {name: "driving",       attribute: "agility"},
  {name: "fighting",      attribute: "agility"},
  {name: "gambling",      attribute: "smarts"},
  {name: "healing",       attribute: "smarts"},
  {name: "intimidation",  attribute: "spirit"},
  {name: "investigation", attribute: "smarts"},
  {name: "knowledge",     attribute: "smarts"},
  {name: "lockpicking",   attribute: "agility"},
  {name: "notice",        attribute: "smarts"},
  {name: "persuasion",    attribute: "spirit"},
  {name: "piloting",      attribute: "agility"},
  {name: "repair",        attribute: "smarts"},
  {name: "riding",        attribute: "agility"},
  {name: "shooting",      attribute: "agility"},
  {name: "stealth",       attribute: "agility"},
  {name: "streetwise",    attribute: "smarts"},
  {name: "survival",      attribute: "smarts"},
  {name: "swimming",      attribute: "agility"},
  {name: "taunt",         attribute: "smarts"},
  {name: "throwing",      attribute: "agility"},
  {name: "tracking",      attribute: "smarts"}
];
